INSERT INTO mbti_questions (
    stt,
    group_index,
    dimension_pair,
    question_text,
    option_a_text,
    option_a_dimension,
    option_b_text,
    option_b_dimension,
    created_at,
    updated_at
) VALUES
    (1, 0, 'EI', 'Bạn thích công việc kiểu :', 'a. Xã hội, giao tiếp.', 'E', 'b. Thiết kế, nghiên cứu.', 'I', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (2, 1, 'SN', 'Bạn tiếp xúc với một người theo xu hướng :', 'a. Khách quan.', 'S', 'b. Chủ quan', 'N', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (3, 2, 'TF', 'Bạn đánh giá sự việc dựa trên :', 'a. Ý nghĩa, giá trị.', 'F', 'b. Tính logic.', 'T', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (4, 3, 'JP', 'Bạn là người có tác phong :', 'a. Thong thả, thoải mái.', 'P', 'b. Nhanh nhẹn, đúng giờ.', 'J', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (5, 0, 'EI', 'Trong các cuộc giao tiếp, bạn là người:', 'a. Bắt đầu cho cuộc nói chuyện.', 'E', 'b. Chỉ nói khi người khác bắt chuyện.', 'I', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (6, 2, 'TF', 'Bạn là người thế nào :', 'a. Là người có cái đầu lạnh.', 'T', 'b. Là người có trái tim ấm.', 'F', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (7, 3, 'JP', 'Tính cách của bạn :', 'a. Dễ chịu, thoải mái.', 'P', 'b. Nghiêm chỉnh, quả quyết.', 'J', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (8, 1, 'SN', 'Những người có tầm nhìn xa thường:', 'a. Khá thú vị', 'N', 'b. Khó hiểu.', 'S', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (9, 0, 'EI', 'Đối với những người mới gặp, bàn thường :', 'a. Dễ dàng bắt chuyện và trò chuyện nhiều điều cùng họ.', 'E', 'b. Cảm thấy khó khăn và không biết nên nói gì.', 'I', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (10, 1, 'SN', 'Một công việc gây nhàm chán khi:', 'a. Không có quy trình cụ thể.', 'S', 'b. Thiếu tính sáng tạo.', 'N', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (11, 2, 'TF', 'Bạn bị hấp dẫn bởi :', 'a. Sự hòa hợp với mọi người.', 'F', 'b. Sự nhất quán trong suy nghĩ.', 'T', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (12, 1, 'SN', 'Bạn bị lôi cuốn bởi kiểu người :', 'a. Giàu trí tưởng tượng.', 'N', 'b. Nắm bắt tình huống tốt.', 'S', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (13, 0, 'EI', 'Trong các cuộc trò chuyện bạn thường :', 'a. Dè dặt.', 'I', 'b. Thoải mái.', 'E', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (14, 1, 'SN', 'Lựa chọn của bạn có xu hướng :', 'a. Tuân theo chuẩn mực.', 'S', 'b. Đôi lúc không hiểu rõ nguyên nhân.', 'N', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (15, 2, 'TF', 'Trong hai điều sau, điều nào tồi tệ hơn:', 'a. Không công bằng.', 'T', 'b. Tàn nhẫn.', 'F', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (16, 3, 'JP', 'Tính cách nào giống bạn hơn :', 'a. Kiên quyết.', 'J', 'b. Nhẹ nhàng.', 'P', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (17, 0, 'EI', 'Đối với một vấn đề trong nhóm :', 'a. Độc lập giải quyết.', 'I', 'b. Trao đổi với mọi người.', 'E', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (18, 3, 'JP', 'Trong cuộc sống, bạn cảm thấy hứng thú với :', 'a. Những điều bất ngờ không tính trước.', 'P', 'b. Những điều có kế hoặch trước.', 'J', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (19, 2, 'TF', 'Bạn thấy tâm đắc với bản thân bởi sự ', 'a. Chắc chắn trong tư tưởng.', 'T', 'b. Cống hiến hết mình.', 'F', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (20, 1, 'SN', 'Bạn nhìn nhận một vấn đề với :', 'a. Khả năng lý luận phân tích.', 'S', 'b. Sự liên tưởng.', 'N', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (21, 0, 'EI', 'Trong các kỳ nghỉ lễ bạn có xu hướng :', 'a. Ở nhà cùng gia đình.', 'I', 'b. Đi du lịch cùng bạn bè.', 'E', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (22, 1, 'SN', 'Bạn bị lôi cuốn bởi:', 'a. Các ngụ ý, hàm ý, ẩn ý.', 'N', 'b. Các nguyên tắc, nguyên lý.', 'S', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (23, 2, 'TF', 'Khi quyết định việc gì bạn thường dựa vào :', 'a. Cảm nhận từ con tim.', 'F', 'b. Những quy tắc chung.', 'T', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (24, 3, 'JP', 'Bạn thích làm việc với người Sếp :', 'a. Làm việc có phương pháp, tổ chức tốt.', 'J', 'b. Ứng biến xoay trở tốt trước khó khăn.', 'P', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (25, 3, 'JP', 'Bạn nghiêng về :', 'a. Sự chắc chắn.', 'J', 'b. Sự cởi mở.', 'P', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (26, 2, 'TF', 'Bạn là người có tư tưởng :', 'a. Công tư phân minh.', 'T', 'b. Bị tình cảm chi phối.', 'F', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (27, 1, 'SN', 'Bạn thích học các môn :', 'a. Nghệ thuật.', 'N', 'b. Khoa học.', 'S', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (28, 0, 'EI', 'Trong một nhóm bạn bè bạn thường :', 'a. Trầm lặng, ít nói.', 'I', 'b. Hoạt bát, vui vẻ.', 'E', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (29, 1, 'SN', 'Khi đánh giá một người bạn thường :', 'a. Dựa vào vẻ ngoài của họ.', 'S', 'b. Dựa vào cảm nhận của bạn.', 'N', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (30, 2, 'TF', 'Sẽ thật tai hại khi bạn :', 'a. Quá nồng nhiệt, mong chờ.', 'T', 'b. Quá khách quan.', 'F', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (31, 0, 'EI', 'Phong cách của bạn :', 'a. Thích những thứ quen thuộc.', 'I', 'b. Thích những điều mới mẻ.', 'E', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (32, 3, 'JP', 'Khi giải quyết một công việc thông thường, bạn sẽ :', 'a. Tìm kiếm một cách làm mới.', 'P', 'b. Làm theo cách mọi người hay làm.', 'J', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (33, 0, 'EI', 'Bạn thích làm việc :', 'a. Độc lập.', 'I', 'b. Theo nhóm.', 'E', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (34, 1, 'SN', 'Bạn có hành động theo bản năng :', 'a. Hiếm khi.', 'S', 'b. Hay xảy ra.', 'N', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (35, 2, 'TF', 'Trong cuộc sống, một người sẽ tốt hơn nếu :', 'a. Giàu lý trí.', 'T', 'b. Giàu cảm xúc.', 'F', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (36, 3, 'JP', 'Khi nghe một album nhạc mới, bạn thường nghe :', 'a. Theo thứ tự.', 'J', 'b. Phát ngẫu nhiên.', 'P', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (37, 3, 'JP', 'Bạn là người :', 'a. Khéo léo, lanh lợi.', 'P', 'b. Thẳng thắn, thực tế.', 'J', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (38, 2, 'TF', 'Sẽ khó khăn hơn khi bạn cố:', 'a. Sử dụng người khác.', 'F', 'b. Hiểu và chia sẻ với người khác.', 'T', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (39, 0, 'EI', 'Khi cảm thấy buồn bạn thường :', 'a. Tìm bạn bè tâm sự hoặc đi chơi.', 'E', 'b. Muốn ở một mình cho khuây khỏa.', 'I', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (40, 3, 'JP', 'Bạn muốn một sự kiện như thế nào :', 'a. Chuẩn bị chu toàn trước.', 'J', 'b. Diễn ra tự nhiên.', 'P', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (stt) DO UPDATE SET
    group_index = EXCLUDED.group_index,
    dimension_pair = EXCLUDED.dimension_pair,
    question_text = EXCLUDED.question_text,
    option_a_text = EXCLUDED.option_a_text,
    option_a_dimension = EXCLUDED.option_a_dimension,
    option_b_text = EXCLUDED.option_b_text,
    option_b_dimension = EXCLUDED.option_b_dimension,
    created_at = EXCLUDED.created_at,
    updated_at = CURRENT_TIMESTAMP;
